name: Panther Analysis CI/CD workflow for Custom Schemas

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - "data_models/**"
      - "lookup_tables/**"
      - "policies/**"
      - "queries/**"
      - "rules/**"
      - "schemas/**"
      - ".github/workflows/**"

jobs:
  download_pantherlog_tool:
    runs-on: ubuntu-latest
    name: Download the pantherlog tool to use for schema tests
    steps:
      - name: Download pantherlog & unzip
        run: curl -sSO "https://panther-community-us-east-1.s3.amazonaws.com/v1.46.0/tools/linux-amd64-pantherlog.zip" && unzip linux-amd64-pantherlog.zip
      - name: Create a pantherlog artifact
        uses: actions/upload-artifact@v3
        with:
          name: pantherlog
          path: pantherlog
          retention-days: 1
  run_schema_tests:
    runs-on: ubuntu-latest
    name: Run schema tests with pantherlog
    needs: [download_pantherlog_tool]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Download Pantherlog tool from artifacts
        uses: actions/download-artifact@v3
        with:
          name: pantherlog
      - name: Make pantherlog executable
        run: sudo chmod +x pantherlog
      - name: Perform schema tests with pantherlog
        run: ./pantherlog test schemas/
  run_unit_tests:
    runs-on: ubuntu-latest
    name: Run unit tests on detections using the panther_analysis_tool
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install python dependencies and panther_analysis_tool
        run: make install
      - name: Run unit tests for all rule detections
        run: pipenv run panther_analysis_tool test --filter AnalysisType=rule
      - name: Run unit tests for all scheduled rule detections
        run: pipenv run panther_analysis_tool test --filter AnalysisType=scheduled_rule
      - name: Run unit tests for all policy detections
        run: pipenv run panther_analysis_tool test --filter AnalysisType=policy
  panther_analysis_tool_upload:
    runs-on: ubuntu-latest
    name: Upload detections to panther console using panther_analysis_tool
    needs: [download_pantherlog_tool, run_schema_tests, run_unit_tests]
    env:
      PANTHER_API_TOKEN: ${{ secrets.PANTHER_API_TOKEN }}
      PANTHER_API_HOST: "https://52kapw7yz3.execute-api.eu-west-1.amazonaws.com/v1/public/graphql"
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install python dependencies and panther_analysis_tool
        run: make install
      - name: Upload rules from the detections folder to your Panther instance
        run: pipenv run panther_analysis_tool upload --skip-tests
      - name: Upload custom schemas to Panther Console
        run: pipenv run panther_analysis_tool update-custom-schemas --path schemas/
